### ISSUE TITLE
kubed image missing from registry

### ISSUE THREAD

**Issue by nomaster** [appscode/charts#1081]
When installing kubed with Helm, I get the following error:

> Failed to pull image "appscode/kubed:v0.13.2": failed to pull and unpack image "docker.io/appscode/kubed:v0.13.2": failed to resolve reference "docker.io/appscode/kubed:v0.13.2": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

I found that on the [appscode Docker Hub page](https://hub.docker.com/u/appscode), there is no repository 'kubed' listed.

**Comment by tamalsaha** [comment]
The old Kubed images where showing lots of CVEs for which we were getting support requests. [Open Source Doesn't Require Providing Builds](https://codeengineered.com/blog/2024/open-source-not-builds/). [Open source does not require us to offer free bug fixes or support or take external contribution](https://www.sqlite.org/copyright.html). So, we have deleted those images.

The Config Syncer project is open source under the Apache V2 License and will remain so. You can find the source code here: https://github.com/config-syncer/config-syncer .

Here are few options to go from here:

(1) Get a [free 30 day license from us](https://config-syncer.com/docs/v0.14.6/setup/install/), the maintainers of the project and [buy commercial licenses](https://config-syncer.com/pricing/) to support the people behind the project who have maintained this project since 2017. We guarantee regular updates so all known vulnerabilities are fixed. A license will be required to use our pre-built docker images. I hope you take this option so we can continue to offer this open source software to the world. You can also use the 30 day license to buy time to find another alternative.

(2) Build config syncer images from the source code and/or make necessary changes as your right permitted under the Apache v2 license.

(3) Replace config syncer with something else.

**Comment by nomaster** [comment]
Thanks for the quick response!

We moved to [Kubernetes Replicator](https://github.com/mittwald/kubernetes-replicator)

**Comment by baselbmz** [comment]
I like the solution of deleting images because they have CVEs. Next time I have a virus in my head I'll cut my head.
